### ISSUE TITLE
Paths in Windows got a "\" which might lead to wrong interpretations

### ISSUE THREAD

**Issue by jfthuong** [wk-j/vscode-save-and-run#17]
Hi, great program!

I use VS Code on Windows and trouble using paths (relative or absolute).

I have the following configuration

```json
            {
                "match": "\\.adoc$",
                "cmd": "asciidoctor ${file}",
                "useShortcut": false,
                "silent": false
            }
```

And this leads to following output in Terminal

> $ asciidoctor c:\dir1\dir2/myfile.adoc
> asciidoctor: FAILED: input file c:dir1dir2/myfile.adoc is missing

Any suggestion on how to do?

**Comment by igor-tm** [comment]
I had same problem when running in mingw. Using single quotes did the trick:
"cmd": "echo changed '${file}'",

**Comment by jfthuong** [comment]
Interesting idea @igor-tm !

Actually, I managed to solve by simply adding an escaped double quote

```json
            {
                "match": "\\.adoc$",
                "cmd": "asciidoctor \"${file}\"",
                "useShortcut": false,
                "silent": false
            }
```

And so, probably also works with single quote (not tested yet):

```json
            {
                "match": "\\.adoc$",
                "cmd": "asciidoctor '${file}'",
                "useShortcut": false,
                "silent": false
            }
```
