### ISSUE TITLE
Commands get entered in editor window

### ISSUE THREAD

**Issue by andrewatwood** [wk-j/vscode-save-and-run#3]
On occasion, a command will be entered at the bottom of the currently open file instead of the terminal window. Can't seem to figure out when.

**Comment by wk-j** [comment]
Have you installed latest version of vscode?

**Comment by andrewatwood** [comment]
I have - will keep an eye out and report back if it happens again.

**Comment by andrewatwood** [comment]
Running latest - got it to happen yesterday. Happens on HTML files more than anything if that matters. Always gets inserted as a new last line.
