### ISSUE TITLE
Doesn't work when default terminal is BASH

### ISSUE THREAD

**Issue by khanzzirfan** [wk-j/vscode-save-and-run#37]
When bash is the default terminal, the workspace folder looses all the '//' for folders. All the path variables looses '//'.

**Comment by raschmitt** [comment]
Would it be possible to run commands directly on bash instead of cmd?

**Comment by raschmitt** [comment]
Same issue here

**Comment by khanzzirfan** [comment]
Solves the problem. Thanks

**Comment by khanzzirfan** [comment]
Solves the problem. Thanks
