### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by rodrigopandini** [wk-j/vscode-save-and-run#5]
Stop working and just paste the copied content that are in the transfer area to the command line.
There is some way to check if some other extension are affecting it?

**Comment by wk-j** [comment]
Sorry I don't understand
You mean It just copy command into terminal area but not execute the command?

**Comment by rodrigopandini** [comment]
It just paste the content that are in the transfer area (Ctrl+c) into terminal.
Don't execute anything.

**Comment by wk-j** [comment]
Strange !!!

This extension will overwrite your clipboard with specific command (your config) 
Look like https://github.com/xavi-/node-copy-paste not working correctly on your system.

**Comment by rodrigopandini** [comment]
yeah, strange!
I'm in Ubuntu 16.04 LTS, 64bits.
I'm not using any other extensions that ovewrite the clipboard.
Here is my `settings.json`:
```json
{
    "workbench.iconTheme": "vscode-icons",
    "saveAndRun": {
        "commands": [
            {
                "match": ".*",
                "cmd": "npm run vendor"
            }
        ]
    },
    "typescript.check.npmIsInstalled": false
}
```

**Comment by wk-j** [comment]
Hi @rodrigopandini 

In ubuntu you have to install xclip because it for node-copy-paste https://github.com/xavi-/node-copy-paste/issues/56

**Comment by rodrigopandini** [comment]
Yes. Works again!
Thank you.
